// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mxcmnuujbqgegtzpugxo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im14Y21udXVqYnFnZWd0enB1Z3hvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwOTg4NjgsImV4cCI6MjA2NDY3NDg2OH0.pHC1KQZVEqpG1DJ5mINZIKqJrRg0yRo8MvVfGw6EpCE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);